name: CI
blank.yml
on: [push]
blank.yml
jobs:blank.yml
  build:blank.yml
blank.yml
    runs-on: ubuntu-latest

    steps: blank.yml
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |blank.yml
        echo Add other actions to build,
        echo test, and deploy your project.
